### ISSUE TITLE
Hyku rake demo aborts

### ISSUE THREAD

**Issue by seth-shaw-unlv** [samvera-deprecated/samvera-vagrant#19]
A fresh clone of samvera-vagrant and vagrant up produce a rake aborted error:
```
==> default: Cloning into 'hyku-demo'...
==> default: The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
==> default: To update, run `gem install bundler --pre`
==> default: rake aborted!
==> default: Gem::LoadError: You have already activated rake 12.1.0, but your Gemfile requires rake 12.0.0. Prepending `bundle exec` to your command may solve this.
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:317:in `check_for_activated_spec!'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:32:in `block in setup'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `map'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `setup'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/config/boot.rb:3:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/config/application.rb:1:in `require_relative'
==> default: /home/ubuntu/hyku-demo/config/application.rb:1:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/Rakefile:4:in `<top (required)>'
==> default: /var/lib/gems/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
==> default: LoadError: cannot load such file -- bundler/setup
==> default: /home/ubuntu/hyku-demo/config/boot.rb:3:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/config/application.rb:1:in `require_relative'
==> default: /home/ubuntu/hyku-demo/config/application.rb:1:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/Rakefile:4:in `<top (required)>'
==> default: /var/lib/gems/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
==> default: (See full trace by running task with --trace)
==> default: rake aborted!
==> default: Gem::LoadError: You have already activated rake 12.1.0, but your Gemfile requires rake 12.0.0. Prepending `bundle exec` to your command may solve this.
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:317:in `check_for_activated_spec!'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:32:in `block in setup'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `map'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `setup'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
==> default: /var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/config/boot.rb:3:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/config/application.rb:1:in `require_relative'
==> default: /home/ubuntu/hyku-demo/config/application.rb:1:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/Rakefile:4:in `<top (required)>'
==> default: /var/lib/gems/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
==> default: LoadError: cannot load such file -- bundler/setup
==> default: /home/ubuntu/hyku-demo/config/boot.rb:3:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/config/application.rb:1:in `require_relative'
==> default: /home/ubuntu/hyku-demo/config/application.rb:1:in `<top (required)>'
==> default: /home/ubuntu/hyku-demo/Rakefile:4:in `<top (required)>'
==> default: /var/lib/gems/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
==> default: (See full trace by running task with --trace)
```

SSHing into the VM and running cd hyku-demo; rake demo gives a similar error
```
rake aborted!
Gem::LoadError: You have already activated rake 12.1.0, but your Gemfile requires rake 12.0.0. Prepending `bundle exec` to your command may solve this.
/var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:317:in `check_for_activated_spec!'
/var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:32:in `block in setup'
/var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `map'
/var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/runtime.rb:27:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:101:in `setup'
/var/lib/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/setup.rb:9:in `<top (required)>'
/home/ubuntu/hyku-demo/config/boot.rb:3:in `<top (required)>'
/home/ubuntu/hyku-demo/config/application.rb:1:in `require_relative'
/home/ubuntu/hyku-demo/config/application.rb:1:in `<top (required)>'
/home/ubuntu/hyku-demo/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/ubuntu/hyku-demo/config/boot.rb:3:in `<top (required)>'
/home/ubuntu/hyku-demo/config/application.rb:1:in `require_relative'
/home/ubuntu/hyku-demo/config/application.rb:1:in `<top (required)>'
/home/ubuntu/hyku-demo/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

Running vagrant 1.9.8 on OS X 10.12.6 with VirtualBox 5.1.22

**Comment by seth-shaw-unlv** [comment]
Attaching the full vagrant up output...
[vagrant-up-out.txt](https://github.com/samvera-labs/samvera-vagrant/files/1300878/vagrant-up-out.txt)

**Comment by apatsekin** [comment]
Same issue here:

> `==> default: rake aborted!
==> default: Gem::LoadError: You have already activated rake 12.1.0, but your Gemfile requires rake 12.0.0. Prepending `bundle exec` to your command may solve this.`

MacOS Sierra 10.12.5; Vagrant 1.9.2; VirtualBox 5.1.28
