### ISSUE TITLE
Problem with sassc

### ISSUE THREAD

**Issue by whikloj** [samvera-deprecated/samvera-vagrant#31]
Long time listener, first time caller.

Was trying to setup a small Hyrax to investigate an issued raised to the Fedora team.

Cloned this repo and did `vagrant up`

Was going along good until...

```
 default: Bundle complete! 14 Gemfile dependencies, 69 gems now installed.
    default: Use `bundle info [gemname]` to see where a bundled gem is installed.
    default: Post-install message from sass:
    default: 
    default: Ruby Sass has reached end-of-life and should no longer be used.
    default: 
    default: * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
    default:   primary implementation: https://sass-lang.com/install
    default: 
    default: * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
    default:   sassc gem: https://github.com/sass/sassc-ruby#readme
    default: 
    default: * For more details, please refer to the Sass blog:
    default:   https://sass-lang.com/blog/posts/7828841
    default: Gem::InstallError: sassc requires Ruby version >= 2.3.3.
    default: An error occurred while installing sassc (2.0.1), and Bundler cannot continue.
    default: Make sure that `gem install sassc -v '2.0.1' --source 'https://rubygems.org/'`
    default: succeeds before bundling.
    default: 
    default: In Gemfile:
    default:   hyrax was resolved to 3.0.0.pre.beta2, which depends on
    default:     hydra-head was resolved to 10.6.2, which depends on
    default:       hydra-core was resolved to 10.6.2, which depends on
    default:         hydra-access-controls was resolved to 10.6.2, which depends on
    default:           blacklight-access_controls was resolved to 0.6.2, which depends on
    default:             blacklight was resolved to 6.20.0, which depends on
    default:               bootstrap-sass was resolved to 3.4.1, which depends on
    default:                 sassc
    default: /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/source/git/git_proxy.rb:235:in `allowed_in_path'
    default: : 
    default: The git source https://github.com/samvera/hyrax.git is not yet checked out. Please run `bundle install` before trying to start your application
    default:  (
    default: Bundler::GitError
    default: )
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/source/git/git_proxy.rb:192:in `find_local_revision'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/source/git/git_proxy.rb:64:in `revision'
    default: 	from /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/source/git.rb:225:in `revision'
    ...
```

Then it tries to continue and fails referencing the missing `sassc`

```
default: Creating Hyku demo in /home/vagrant/hyku-demo
    default: Cloning into 'hyku-demo'...
    default: Gem::InstallError: sassc requires Ruby version >= 2.3.3.
    default: An error occurred while installing sassc (2.0.1), and Bundler cannot continue.
    default: Make sure that `gem install sassc -v '2.0.1' --source 'https://rubygems.org/'`
    default: succeeds before bundling.
    default: 
    default: In Gemfile:
    default:   hyrax was resolved to 2.3.3, which depends on
    default:     hydra-head was resolved to 10.5.1, which depends on
    default:       hydra-core was resolved to 10.5.1, which depends on
    default:         hydra-access-controls was resolved to 10.5.1, which depends on
    default:           blacklight-access_controls was resolved to 0.6.2, which depends on
    default:             blacklight was resolved to 6.15.0, which depends on
    default:               bootstrap-sass was resolved to 3.4.1, which depends on
    default:                 sassc
    default: /var/lib/gems/2.3.0/gems/bundler-2.0.1/lib/bundler/spec_set.rb:87:in `block in materialize'
    default: : 
    default: Could not find sassc-2.0.1 in any of the sources
    default:  (
    default: Bundler::GemNotFound
    default: )
```

Which makes sense as it complained about that thing as it was trying to install it.

Anyways, I'm a little lost as to what the fastest way to correct this would be?

**Comment by cajunjoel** [comment]
After getting the same error as @whikloj, I manually copied the [install_scripts/demo-app.sh](https://github.com/samvera-labs/samvera-vagrant/blob/master/install_scripts/demo-app.sh) into my server to run it by hand.  When I ran it, I got the following results:

```
Gem::InstallError: sassc requires Ruby version >= 2.3.3.
An error occurred while installing sassc (2.0.1), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.0.1' --source 'https://rubygems.org/'`
succeeds before bundling.
```


Well that's interesting. Something is now trying to install the sassc gem, which sort of resolves the issue reported by @whikloj but, it requires a newer version of ruby than what Ubuntu installs.

And checking my ruby version...

```
vagrant@samvera:~$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
vagrant@samvera:~$ dpkg -l | fgrep ruby
ii  ruby                              1:2.3.0+1                                  all
ii  ruby2.3                           2.3.1-2~16.04.12                           amd64
```

To work around this, I added a new repo for ruby:

```
sudo apt-add-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.2 ruby2.2-dev
```

Now my ruby version is:

```
vagrant@samvera:~$ ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux-gnu]
```

And then I re-ran the copy of `install_scripts/demo-app.sh` that I'd copied into my Vagrant VM. It's not a great solution and I don't understand why sassc is suddenly being used when it wasn't selected during the initial setup.

This seems to have worked around the issue. Everything built and configured with a few `already initialized constant` warnings.

**Comment by whikloj** [comment]
Hey @cajunjoel,

I went to the samvera #hyku channel and was told that this is out of date and they recommend the [hyku](https://github.com/samvera/hyku) docker setup to try out Hyrax.

**Comment by escowles** [comment]
@cajunjoel @whikloj This project may have outlived its usefulness — I'd happily merge a PR to fix this particular issue.  But maybe I should just post a deprecation notice and start the process of moving it to https://github.com/samvera-deprecated ?

**Comment by whikloj** [comment]
@escowles I unfortunately don't have the knowledge of the Samvera stack to start debugging this. You do what makes the most sense for the Samvera community.

**Comment by no-reply** [comment]
:+1: to moving this to `deprecated`, in lieu of a maintainer
